### ISSUE TITLE
advertise the event

### ISSUE THREAD

**Issue by lsetiawan** [geohackweek/administrative#20]
To maximize diversity of applicants we recommend advertising the event as widely as possible. Use listservers, Twitter, institutional websites, posters around campus, word of mouth.

**Comment by aaarendt** [comment]
## Here's the lists we've hit in the past:

cryolist@lists.cryolist.org
glaciology@u.washington.edu
climlist
gilbertclub@lists.berkeley.edu
escience_bbl@u.washington.edu
escience_allhands@uw.edu
escience_affiliates@uw.edu
Staffcfr@uw.edu
sefsgrads@uw.edu
sefsunder@uw.edu
faccfr@uw.edu
eScience website
futureofice@uw.edu
pi-list@apl.washington.edu
polar science center website
jobsnancycaitlin@googlegroups.com
python_for_geoscience@u.washington.edu
cugos@googlegroups.com
undertow@ocean.washington.edu
ocean_grads@ocean.washington.edu
ess_grads@uw.edu
https://groups.google.com/forum/#!forum/ioos_tech
siam-gs@siam.org

**Comment by aaarendt** [comment]
Here's the template letter we've used in the past:

Hello,

The University of Washington’s eScience Institute is hosting a GeoHackweek, Sept 11 - 15, 2017. Join us for five days of tutorials, data exploration, software development and community networking, focused on open source tools to analyze and visualize geospatial data. Our event will include instructors from academia and industry across many different geospatial disciplines.  
 
Please visit our website https://geohackweek.github.io/ for details on how to apply.

Application deadline: June 15, 2017

We look forward to seeing you in Seattle!

Anthony Arendt
