### ISSUE TITLE
design an application form

### ISSUE THREAD

**Issue by lsetiawan** [geohackweek/administrative#7]
- [x] read Daniela Huppenkothen's post on [participant selection](https://danielahuppenkothen.wordpress.com/2016/11/16/workshop-participant-selection-from-start-to-finish-an-example/)
- [x] choose a survey platform. We recommend Google forms or jotform (which allows for users to attach files, e.g. a CV)
- [x] design the application form. Consult with prior hackweek organizers regarding how best to design applications that maximize diversity and minimize potential for bias. See examples from [geo](https://form.jotform.com/geohack/2018)  and [neuro](https://form.jotform.com/80126067304145) hackweeks.

Note that we have formatted the application to contain categorical inputs so that these responses can be input into the [Entrofy algorithm](https://github.com/dhuppenkothen/entrofy) we use to assist in applicant selection.

**Comment by aaarendt** [comment]
Form is here: https://form.jotform.com/geohack/2018
